name: CI/CD deploy

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: Build and test Docker image
    runs-on: self-hosted

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t devops-lab-service:ci -f docker/Dockerfile .

      - name: Run container for test
        run: |
          docker rm -f devops-lab-ci-test || true
          docker run -d \
            --name devops-lab-ci-test \
            -p 18000:8000 \
            devops-lab-service:ci

      - name: Check application
        run: |
          sleep 5
          curl -f http://localhost:18000/

      - name: Check metrics
        run: |
          curl -f http://localhost:18000/metrics

      - name: Stop test container
        if: always()
        run: |
          docker rm -f devops-lab-ci-test || true

  deploy:
    name: Deploy to VM through SSH
    runs-on: self-hosted
    needs: ci

    steps:
      - name: Deploy on virtual machine
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/devops-lab-service
            git pull origin master
            cd docker
            docker compose up -d --build
            docker compose ps
