name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Show Docker version
        run: |
          docker --version
          docker compose version

      - name: Build Docker image
        run: |
          docker build -t devops-lab-service:latest -f docker/Dockerfile .

      - name: Stop old containers
        run: |
          cd docker
          docker compose down || true

      - name: Start updated service
        run: |
          cd docker
          docker compose up -d --build

      - name: Check containers
        run: |
          cd docker
          docker compose ps

      - name: Check application
        run: |
          sleep 5
          curl -f http://localhost:8000/

      - name: Check metrics
        run: |
          curl -f http://localhost:8000/metrics
